namespace: elastio
name: bac
version: 0.1.1
readme: README.md
authors:
  - Greg Wojtak (https://github.com/gwojtak)
  - Robert Saylor (https://github.com/rsaylor73/elastio)
description: Ansible collection for the Elastio CLI
license_file: COPYING
tags: [elastio, backup]
repository: https://github.com/rsaylor73/elastio
documentation: null
homepage: https://github.com/rsaylor73/elastio
issues: null
